//! hauksbee-mcu: generalized MCU emulation bridge.
//!
//! Provides a [`Mcu`] trait for driving a simulated microcontroller, plus two
//! backends behind the uniform trait:
//!   - [`AvrMcu`] (feature `avr`): in-process AVR via libsimavr FFI.
//!   - [`RenodeBackend`] (feature `renode`): STM32 / nRF52 / RISC-V (and more)
//!     by driving an external headless Renode process over its Monitor TCP
//!     protocol and a UART socket terminal.
//!   - [`QemuBackend`] (feature `qemu`): ESP32 family (Xtensa ESP32/S3 and
//!     RISC-V ESP32-C3) by driving an external Espressif QEMU process over QMP +
//!     gdbstub control channels and a UART socket. Renode ships no ESP32
//!     platform, so this is the ESP32 path.
//!
//! Both backends present the identical lockstep surface (`run_micros`, GPIO/
//! ADC/UART exchange via [`PinId`] and byte streams), so the engine scheduler
//! couples to either without change. All board-specific logic (MCP4728 decode,
//! 74HC595 readback, neuron simulation) lives in higher-level crates; this
//! crate is pure emulation plumbing.
//!
//! # Licensing note
//! With the `avr` feature, this crate links libsimavr (GPL-3.0) and any binary
//! built from it is subject to the GPL. The `renode` backend links nothing
//! native (it talks to Renode over sockets), so a `--no-default-features
//! --features renode` build is GPL-free.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

/// Raw simavr FFI bindings generated by bindgen.
#[cfg(feature = "avr")]
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/simavr_bindings.rs"));
}

#[cfg(feature = "avr")]
pub mod avr;
pub mod elf;
pub mod traits;

#[cfg(feature = "renode")]
pub mod renode;

#[cfg(feature = "qemu")]
pub mod qemu;

/// Data-driven MCU/SoC descriptors: the `db/mcu/*.soc.toml` loader (06 §2).
pub mod soc;

pub use traits::{I2cEvent, Mcu, McuState, PinId, SpiEvent};

use std::path::{Path, PathBuf};

/// Resolve `path` to an absolute form for error messages, without requiring the
/// file to exist (so `canonicalize` is not an option: it fails on a missing
/// path). A relative path is joined onto the current working directory.
fn absolutize(path: &Path) -> PathBuf {
    std::path::absolute(path).unwrap_or_else(|_| {
        if path.is_absolute() {
            path.to_path_buf()
        } else {
            std::env::current_dir()
                .map(|d| d.join(path))
                .unwrap_or_else(|_| path.to_path_buf())
        }
    })
}

/// Validate a firmware path BEFORE it is handed to a native emulator backend.
///
/// simavr's `read_ihex_file` / `elf_read_firmware` (and the QEMU/Renode loaders)
/// do not defend against a missing file: given a path that does not exist they
/// print libc's "No such file or directory" to stderr and then dereference a
/// null result, crashing the whole process with SIGSEGV (exit 139) instead of
/// returning an error. This guard turns that into a clean, actionable failure.
///
/// On success it returns the resolved absolute path (the caller can canonicalize
/// it further once existence is guaranteed). On failure the error names the
/// absolute path that was tried and says whether it was missing, a directory,
/// or unreadable. Callers with extra provenance (e.g. a CI spec field) should
/// wrap this error to add where the path came from.
pub fn validate_firmware_path(path: &Path) -> anyhow::Result<PathBuf> {
    let abs = absolutize(path);
    match std::fs::metadata(path) {
        Ok(md) => {
            if md.is_dir() {
                anyhow::bail!(
                    "firmware path is a directory, not a file: {}",
                    abs.display()
                );
            }
            // Readability: open it now so a permission problem surfaces here with
            // a clean message rather than deep inside the native loader.
            std::fs::File::open(path).map_err(|e| {
                anyhow::anyhow!("firmware file is not readable: {} ({e})", abs.display())
            })?;
            Ok(abs)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            anyhow::bail!("no firmware file at {}", abs.display())
        }
        Err(e) => anyhow::bail!("cannot access firmware file {}: {e}", abs.display()),
    }
}

#[cfg(feature = "avr")]
pub use avr::AvrMcu;

#[cfg(feature = "renode")]
pub use renode::{AdcChannelMap, AdcInject, RenodeBackend, RenodeConfig};

#[cfg(feature = "qemu")]
pub use qemu::{QemuBackend, QemuConfig};

pub use soc::{Backend, SocConfig, SocError};

#[cfg(test)]
mod firmware_guard_tests {
    use super::validate_firmware_path;
    use std::path::Path;

    #[test]
    fn missing_file_errors_with_absolute_path() {
        let err = validate_firmware_path(Path::new("definitely_missing_firmware.hex"))
            .expect_err("missing firmware must error");
        let msg = err.to_string();
        assert!(msg.contains("no firmware file"), "message: {msg}");
        // The tried path is reported absolutely, not as the bare relative typo.
        assert!(msg.contains("definitely_missing_firmware.hex"), "message: {msg}");
        assert!(
            Path::new(msg.rsplit(' ').next().unwrap_or("")).is_absolute()
                || msg.contains('/'),
            "message names an absolute path: {msg}"
        );
    }

    #[test]
    fn directory_is_rejected() {
        let dir = std::env::temp_dir();
        let err = validate_firmware_path(&dir).expect_err("a directory is not firmware");
        assert!(err.to_string().contains("directory"), "message: {err}");
    }

    #[test]
    fn readable_file_is_accepted_and_absolutized() {
        let mut path = std::env::temp_dir();
        path.push(format!("hauksbee-fw-guard-{}.hex", std::process::id()));
        std::fs::write(&path, b":00000001FF\n").expect("write temp firmware");
        let resolved = validate_firmware_path(&path).expect("existing readable file is valid");
        assert!(resolved.is_absolute());
        let _ = std::fs::remove_file(&path);
    }
}
