//! Ship the repo integrations from the tool itself.
//!
//! `hauksbee-ci hook install` wires the pre-commit gate into the current
//! repository (the pre-commit framework's config when the repo uses it, a
//! plain `.git/hooks/pre-commit` otherwise), and `hauksbee-ci github-action`
//! prints (or writes) the GitHub workflow. Both are idempotent: running them
//! twice changes nothing and says so.
//!
//! The canonical integration sources live in `integrations/` at the repo
//! root; what this module emits is the minimal entry that consumes them.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context};

/// The marker every artifact we write carries, so a re-run can recognise its
/// own work (and a human can see where the block came from).
const MARKER: &str = "hauksbee-ci hook install";

/// Walk up from `start` to the repository root (the first directory that
/// contains `.git`).
pub fn find_repo_root(start: &Path) -> Option<PathBuf> {
    let mut dir = start.canonicalize().ok()?;
    loop {
        if dir.join(".git").exists() {
            return Some(dir);
        }
        if !dir.pop() {
            return None;
        }
    }
}

/// Is the pre-commit gate already wired in this repo (either framework
/// config or plain hook mentioning hauksbee)?
pub fn hook_wired(root: &Path) -> bool {
    let config = root.join(".pre-commit-config.yaml");
    if let Ok(text) = fs::read_to_string(&config) {
        if text.contains("hauksbee") {
            return true;
        }
    }
    let hook = root.join(".git/hooks/pre-commit");
    matches!(fs::read_to_string(&hook), Ok(text) if text.contains("hauksbee"))
}

/// Is a GitHub workflow that runs hauksbee already present?
pub fn action_wired(root: &Path) -> bool {
    let dir = root.join(".github/workflows");
    let Ok(entries) = fs::read_dir(&dir) else {
        return false;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let is_workflow = path
            .extension()
            .is_some_and(|e| e == "yml" || e == "yaml");
        if is_workflow {
            if let Ok(text) = fs::read_to_string(&path) {
                if text.contains("hauksbee") {
                    return true;
                }
            }
        }
    }
    false
}

/// The `.pre-commit-config.yaml` repos entry for the hauksbee hooks. The two
/// hook ids are declared in `.pre-commit-hooks.yaml` of the hauksbee repo;
/// `hauksbee-ci` is the spec-driven one this tool exists for.
fn pre_commit_entry() -> String {
    format!(
        "  - repo: https://github.com/hauksbee-dev/hauksbee\n\
         \x20   rev: v{}\n\
         \x20   hooks:\n\
         \x20     - id: hauksbee-ci\n",
        env!("CARGO_PKG_VERSION")
    )
}

/// The plain `.git/hooks/pre-commit` script: run the checked-in specs when a
/// staged file could affect them. Self-contained POSIX sh, no framework.
fn plain_hook_script() -> String {
    format!(
        "#!/bin/sh\n\
         # {MARKER}: block the commit when a staged change breaks a hauksbee-ci spec.\n\
         # Re-running `hauksbee-ci hook install` is a no-op; delete this block to remove.\n\
         if ! command -v hauksbee-ci >/dev/null 2>&1; then\n\
         \x20 echo 'hauksbee-ci: binary not on PATH; skipping hardware check' >&2\n\
         \x20 exit 0\n\
         fi\n\
         staged=$(git diff --cached --name-only --diff-filter=ACMR)\n\
         [ -z \"$staged\" ] && exit 0\n\
         case \"$staged\" in\n\
         \x20 *.kicad_pcb*|*.kicad_sch*|*.net*|*.brd*|*.d356*|*.PcbDoc*|*.board*|*.toml*|*.hex*|*.elf*)\n\
         \x20   # A hauksbee-ci spec is a TOML file with a top-level `board = ...`.\n\
         \x20   specs=$(grep -l '^board *=' ci/*.toml *.toml 2>/dev/null || true)\n\
         \x20   if [ -n \"$specs\" ]; then\n\
         \x20     hauksbee-ci run $specs || exit $?\n\
         \x20   fi\n\
         \x20   ;;\n\
         esac\n\
         exit 0\n"
    )
}

/// The GitHub workflow YAML `github-action` prints/writes. `mode: auto` in
/// the action detects the repo's spec or board, so the generated file needs
/// no per-repo editing to start.
pub fn github_workflow_yaml() -> String {
    format!(
        "# Hardware CI: run hauksbee-ci on every change that could break the board.\n\
         # Generated by `hauksbee-ci github-action`; see the action's README for\n\
         # spec/board/matrix options (integrations/github-action in the hauksbee repo).\n\
         name: hauksbee\n\
         \n\
         # checks: write publishes the JUnit results to the Checks tab. On a fork\n\
         # PR the token is read-only; pass publish-report: false there.\n\
         permissions:\n\
         \x20 contents: read\n\
         \x20 checks: write\n\
         \n\
         on:\n\
         \x20 push:\n\
         \x20 pull_request:\n\
         \n\
         jobs:\n\
         \x20 hauksbee:\n\
         \x20   runs-on: ubuntu-latest\n\
         \x20   steps:\n\
         \x20     - uses: actions/checkout@v4\n\
         \x20     - uses: hauksbee-dev/hauksbee/integrations/github-action@v{}\n\
         \x20       with:\n\
         \x20         junit: hauksbee-ci-results.xml\n",
        env!("CARGO_PKG_VERSION")
    )
}

/// `hauksbee-ci hook install`: wire the pre-commit gate into the repo that
/// contains `cwd`. Detects which hook mechanism the repo uses: a
/// `.pre-commit-config.yaml` gets the framework entry, anything else gets a
/// plain `.git/hooks/pre-commit`. Idempotent both ways.
pub fn hook_install(cwd: &Path) -> anyhow::Result<String> {
    let Some(root) = find_repo_root(cwd) else {
        bail!(
            "not inside a git repository (no .git found walking up from {}); \
             run this from the repo you want the hook in",
            cwd.display()
        );
    };
    let config = root.join(".pre-commit-config.yaml");
    if config.exists() {
        let text = fs::read_to_string(&config)
            .with_context(|| format!("reading {}", config.display()))?;
        if text.contains("hauksbee") {
            return Ok(format!(
                "already installed: {} already references hauksbee; nothing changed",
                config.display()
            ));
        }
        // Insert the entry directly under the top-level `repos:` key, so it
        // stays inside the list no matter what follows the list in the file.
        let entry = pre_commit_entry();
        let new_text = if let Some(pos) = text
            .lines()
            .position(|l| l.trim_end() == "repos:")
        {
            let mut lines: Vec<&str> = text.lines().collect();
            lines.insert(pos + 1, entry.trim_end());
            let mut joined = lines.join("\n");
            joined.push('\n');
            joined
        } else {
            let mut t = text.clone();
            if !t.ends_with('\n') {
                t.push('\n');
            }
            t.push_str("repos:\n");
            t.push_str(&entry);
            t
        };
        fs::write(&config, new_text)
            .with_context(|| format!("writing {}", config.display()))?;
        return Ok(format!(
            "added the hauksbee-ci hook to {}; run `pre-commit install` to activate it",
            config.display()
        ));
    }

    // No pre-commit framework: plain git hook.
    let hooks_dir = root.join(".git/hooks");
    fs::create_dir_all(&hooks_dir)
        .with_context(|| format!("creating {}", hooks_dir.display()))?;
    let hook = hooks_dir.join("pre-commit");
    if hook.exists() {
        let text =
            fs::read_to_string(&hook).with_context(|| format!("reading {}", hook.display()))?;
        if text.contains(MARKER) {
            return Ok(format!(
                "already installed: {} carries the hauksbee-ci block; nothing changed",
                hook.display()
            ));
        }
        // Preserve the existing hook: append our block (minus the shebang).
        let block = plain_hook_script();
        let block_body = block.strip_prefix("#!/bin/sh\n").unwrap_or(&block);
        let mut new_text = text.clone();
        if !new_text.ends_with('\n') {
            new_text.push('\n');
        }
        new_text.push('\n');
        // The appended block must not `exit 0` past any hook logic that
        // follows it in future edits; as the last block that is fine, and the
        // early exits inside only fire on failure.
        new_text.push_str(block_body);
        fs::write(&hook, new_text)
            .with_context(|| format!("writing {}", hook.display()))?;
        set_executable(&hook)?;
        return Ok(format!(
            "appended the hauksbee-ci block to your existing {}",
            hook.display()
        ));
    }
    fs::write(&hook, plain_hook_script())
        .with_context(|| format!("writing {}", hook.display()))?;
    set_executable(&hook)?;
    Ok(format!("installed {}", hook.display()))
}

#[cfg(unix)]
fn set_executable(path: &Path) -> anyhow::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = fs::metadata(path)?.permissions();
    perms.set_mode(perms.mode() | 0o111);
    fs::set_permissions(path, perms)?;
    Ok(())
}

#[cfg(not(unix))]
fn set_executable(_path: &Path) -> anyhow::Result<()> {
    Ok(())
}

/// `hauksbee-ci github-action --write <path>`: write the workflow file.
/// Idempotent: an identical existing file is a no-op; a different one is
/// refused rather than clobbered.
pub fn github_action_write(path: &Path) -> anyhow::Result<String> {
    let yaml = github_workflow_yaml();
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == yaml {
            return Ok(format!("already up to date: {}", path.display()));
        }
        bail!(
            "{} exists with different content; not overwriting. Remove it (or \
             pick another --write path) and re-run, or merge by hand from \
             `hauksbee-ci github-action` on stdout",
            path.display()
        );
    }
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
    }
    fs::write(path, yaml).with_context(|| format!("writing {}", path.display()))?;
    Ok(format!("wrote {}", path.display()))
}

/// The one next-step line a GREEN run ends with: point at whichever repo
/// wiring is missing, and stay silent when both the hook and the workflow
/// are already in place (or when there is no repo to wire).
pub fn green_next_step(cwd: &Path) -> Option<String> {
    let root = find_repo_root(cwd)?;
    let hook = hook_wired(&root);
    let action = action_wired(&root);
    match (hook, action) {
        (true, true) => None,
        (false, true) => Some(
            "next: gate commits locally too: `hauksbee-ci hook install`".to_string(),
        ),
        (true, false) => Some(
            "next: gate pushes and PRs: `hauksbee-ci github-action --write` \
             writes .github/workflows/hauksbee.yml"
                .to_string(),
        ),
        (false, false) => Some(
            "next: wire this into your repo: `hauksbee-ci hook install` (pre-commit \
             gate) and `hauksbee-ci github-action --write` (GitHub workflow)"
                .to_string(),
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;

    fn git_repo(dir: &Path) {
        assert!(Command::new("git")
            .args(["init", "-q"])
            .current_dir(dir)
            .status()
            .expect("git init")
            .success());
    }

    #[test]
    fn plain_hook_install_is_idempotent() {
        let tmp = tempfile::tempdir().unwrap();
        git_repo(tmp.path());
        let first = hook_install(tmp.path()).unwrap();
        assert!(first.starts_with("installed"), "{first}");
        let hook = tmp.path().join(".git/hooks/pre-commit");
        let written = fs::read_to_string(&hook).unwrap();
        assert!(written.contains(MARKER));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_ne!(fs::metadata(&hook).unwrap().permissions().mode() & 0o111, 0);
        }
        let second = hook_install(tmp.path()).unwrap();
        assert!(second.starts_with("already installed"), "{second}");
        assert_eq!(fs::read_to_string(&hook).unwrap(), written);
    }

    #[test]
    fn plain_hook_appends_to_existing_hook() {
        let tmp = tempfile::tempdir().unwrap();
        git_repo(tmp.path());
        let hook = tmp.path().join(".git/hooks/pre-commit");
        fs::write(&hook, "#!/bin/sh\necho preexisting\n").unwrap();
        let msg = hook_install(tmp.path()).unwrap();
        assert!(msg.starts_with("appended"), "{msg}");
        let text = fs::read_to_string(&hook).unwrap();
        assert!(text.contains("echo preexisting"));
        assert!(text.contains(MARKER));
    }

    #[test]
    fn pre_commit_config_gets_the_entry_under_repos() {
        let tmp = tempfile::tempdir().unwrap();
        git_repo(tmp.path());
        fs::write(
            tmp.path().join(".pre-commit-config.yaml"),
            "repos:\n  - repo: https://github.com/psf/black\n    rev: 24.1.0\n    hooks:\n      - id: black\n",
        )
        .unwrap();
        let msg = hook_install(tmp.path()).unwrap();
        assert!(msg.contains("pre-commit install"), "{msg}");
        let text = fs::read_to_string(tmp.path().join(".pre-commit-config.yaml")).unwrap();
        let repos_line = text.lines().position(|l| l == "repos:").unwrap();
        let hauksbee_line = text
            .lines()
            .position(|l| l.contains("hauksbee-dev/hauksbee"))
            .unwrap();
        assert_eq!(hauksbee_line, repos_line + 1, "entry sits under repos:\n{text}");
        assert!(text.contains("id: hauksbee-ci"));
        assert!(text.contains("id: black"));
        // Idempotent.
        let again = hook_install(tmp.path()).unwrap();
        assert!(again.starts_with("already installed"), "{again}");
    }

    #[test]
    fn workflow_write_is_idempotent_and_refuses_divergence() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join(".github/workflows/hauksbee.yml");
        let first = github_action_write(&path).unwrap();
        assert!(first.starts_with("wrote"), "{first}");
        let second = github_action_write(&path).unwrap();
        assert!(second.starts_with("already up to date"), "{second}");
        fs::write(&path, "something else\n").unwrap();
        let err = github_action_write(&path).unwrap_err().to_string();
        assert!(err.contains("not overwriting"), "{err}");
    }

    #[test]
    fn green_next_step_names_only_the_missing_wiring() {
        let tmp = tempfile::tempdir().unwrap();
        git_repo(tmp.path());
        let both = green_next_step(tmp.path()).unwrap();
        assert!(both.contains("hook install") && both.contains("github-action"));
        hook_install(tmp.path()).unwrap();
        let action_only = green_next_step(tmp.path()).unwrap();
        assert!(action_only.contains("github-action") && !action_only.contains("hook install"));
        github_action_write(&tmp.path().join(".github/workflows/hauksbee.yml")).unwrap();
        assert_eq!(green_next_step(tmp.path()), None);
    }
}
