//! Multi-EDA extraction: Eagle .brd and IPC-D-356, cross-checked against
//! the native KiCad extraction where both exist for the same board.

use hauksbee_extract::ExtractedBoard;
use std::collections::{BTreeSet, HashMap};
use std::path::PathBuf;

fn read(rel: &str) -> Option<String> {
    let corpus = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../board-corpus");
    std::fs::read_to_string(corpus.join(rel)).ok()
}

#[test]
fn eagle_metro_mini() {
    let Some(src) = read("eagle/MetroMiniRevB.brd") else {
        eprintln!("eagle corpus missing; skipping");
        return;
    };
    let board = ExtractedBoard::from_eagle_brd(&src).unwrap();
    assert!(board.components.len() > 20, "got {}", board.components.len());
    assert!(board.nets.len() > 15, "got {}", board.nets.len());
    let gnd = board.net_by_name("GND").expect("GND signal");
    assert!(board.net_members(gnd.id).len() > 5);
    // The ATmega328 is on this board somewhere.
    assert!(
        board.components.iter().any(|c| {
            c.value.to_uppercase().contains("ATMEGA") || c.lib_id.to_uppercase().contains("ATMEGA")
        }),
        "no ATmega found"
    );
    // Pads got positions from package definitions.
    let with_pos = board
        .components
        .iter()
        .flat_map(|c| &c.pins)
        .filter(|p| p.position.is_some())
        .count();
    assert!(with_pos > 50);
}

#[test]
fn auto_sniff() {
    for (rel, expect_comps) in [
        ("eagle/MetroMiniRevB.brd", 20usize),
        ("kicad-demos-src/demos/pic_programmer/pic_programmer.kicad_pcb", 50),
    ] {
        let Some(src) = read(rel) else { continue };
        let board = ExtractedBoard::from_auto(&src).unwrap();
        assert!(board.components.len() > expect_comps, "{rel}");
    }
}

/// The strongest test we have: the same physical board through two
/// completely different formats must describe the same circuit. KiCad's own
/// IPC-D-356 export (testdata/pic_programmer.d356, generated by kicad-cli
/// 10) is compared against our direct .kicad_pcb extraction.
///
/// D356 uppercases net names and truncates them to 14 characters, so the
/// comparison is structural: for every D356 net, the set of (ref, pin)
/// members must sit on exactly one net in the native extraction.
#[test]
fn ipc356_matches_native_kicad_extraction() {
    let d356_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/pic_programmer.d356");
    let Ok(d356_src) = std::fs::read_to_string(&d356_path) else {
        eprintln!("d356 fixture missing; skipping");
        return;
    };
    let Some(pcb_src) = read("kicad-demos-src/demos/pic_programmer/pic_programmer.kicad_pcb")
    else {
        eprintln!("corpus missing; skipping");
        return;
    };

    let from_d356 = ExtractedBoard::from_ipc_d356(&d356_src).unwrap();
    let native = ExtractedBoard::from_kicad_pcb(&pcb_src).unwrap();

    // (ref, pin) -> native net id
    let mut native_net: HashMap<(String, String), i64> = HashMap::new();
    for c in &native.components {
        for p in &c.pins {
            if let Some(id) = p.net {
                native_net.insert((c.reference.clone(), p.number.clone()), id);
            }
        }
    }

    let mut nets_checked = 0;
    for net in &from_d356.nets {
        let members: Vec<_> = from_d356.net_members(net.id);
        if members.len() < 2 {
            continue;
        }
        let native_ids: BTreeSet<i64> = members
            .iter()
            .filter_map(|(c, p)| {
                native_net.get(&(c.reference.clone(), p.number.clone())).copied()
            })
            .collect();
        assert_eq!(
            native_ids.len(),
            1,
            "D356 net {:?} members {:?} map to multiple native nets {:?}",
            net.name,
            members
                .iter()
                .map(|(c, p)| format!("{}-{}", c.reference, p.number))
                .collect::<Vec<_>>(),
            native_ids
        );
        nets_checked += 1;
    }
    assert!(nets_checked > 20, "only {nets_checked} nets compared");

    // And the totals are sane: every multi-pin native net appears.
    let multi_pin_native = native
        .nets
        .iter()
        .filter(|n| n.id != 0 && native.net_members(n.id).len() >= 2)
        .count();
    assert!(
        (nets_checked as i64 - multi_pin_native as i64).abs() <= 2,
        "net count mismatch: d356 {nets_checked} vs native {multi_pin_native}"
    );
}
