//! Downstream source-compatibility fixture for the pre-release public run API.

use hauksbee_engine::commands::run::RunConfig;

#[test]
fn existing_run_config_struct_literals_still_compile() {
    let _cfg = RunConfig {
        board: "board.kicad_pcb".into(),
        example: None,
        bom: None,
        bom_columns: Vec::new(),
        placement: None,
        firmware: None,
        seconds: 0.2,
        headless: false,
        report: false,
        drc: true,
        ampacity: false,
        lint: false,
        si: false,
        resources: false,
        usb_c: false,
        thermal: false,
        ambient: 25.0,
        plain: false,
        verbose: false,
        json: true,
        strict: false,
        strict_thermal: false,
        no_strict_thermal: false,
        strict_boot: false,
        list_nets: false,
        check: false,
        oracle: false,
        apply_shorts: false,
        serve: false,
        open: false,
        no_open: false,
        tui: false,
        port: 8080,
        models_dir: None,
        ac: None,
        ac_node: Vec::new(),
        ac_csv: None,
        ac_loop: None,
        probe: Vec::new(),
        probe_csv: None,
        chunk_us: None,
        fit: Vec::new(),
        no_fit: Vec::new(),
        dnp_policy: hauksbee_extract::dnp::DnpPolicy::FitExceptLinks,
        serial_attach: false,
        serial_transport: hauksbee_mcu::hostserial::HostSerialTransport::Pty,
        serial_wait: None,
        serial_no_pace: false,
        serial_mcu: None,
        asbuilt: None,
        junit: None,
        sarif: None,
        emit_manifest: None,
        manifest_command: vec!["hauksbee".into(), "run".into()],
    };
}
