//! Schematic extraction tests.
//!
//! Unit tests run on small hand-written fixtures (see `fixtures/`). The
//! decisive tests are the cross-validations: for a corpus project that ships
//! both a `.kicad_sch` hierarchy and a `.kicad_pcb`, the netlist we derive
//! from the schematic must induce the *same partition* of component pins into
//! nets as the layout does. Net names may differ (KiCad's autogenerated
//! `Net-(...)` names depend on annotation order); the partition structure must
//! be identical.

use galvani_extract::{Component, ExtractedBoard};
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::PathBuf;

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../board-corpus")
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

// ---------------------------------------------------------------------------
// Partition comparison machinery
// ---------------------------------------------------------------------------

/// Every (reference, pin) pair that sits on a real (>=2 member) net, grouped
/// by net. Returned as a set of frozen member-sets so two extractions can be
/// compared regardless of net id or name.
fn partition(board: &ExtractedBoard) -> BTreeSet<BTreeSet<(String, String)>> {
    let mut by_net: BTreeMap<i64, BTreeSet<(String, String)>> = BTreeMap::new();
    for c in &board.components {
        for p in &c.pins {
            if let Some(id) = p.net {
                by_net
                    .entry(id)
                    .or_default()
                    .insert((c.reference.clone(), p.number.clone()));
            }
        }
    }
    by_net
        .into_values()
        .filter(|s| s.len() >= 2)
        .collect()
}

/// (ref, pin) -> net id, for pointwise comparison.
fn pin_to_net(board: &ExtractedBoard) -> HashMap<(String, String), i64> {
    let mut m = HashMap::new();
    for c in &board.components {
        for p in &c.pins {
            if let Some(id) = p.net {
                m.insert((c.reference.clone(), p.number.clone()), id);
            }
        }
    }
    m
}

/// Compare the two partitions and return a human-readable diff (empty when
/// they match exactly over their shared pins).
fn diff_partitions(sch: &ExtractedBoard, pcb: &ExtractedBoard) -> Vec<String> {
    let sch_net = pin_to_net(sch);
    let pcb_net = pin_to_net(pcb);

    // Restrict to pins present in both extractions: the PCB may carry mounting
    // holes / test points the schematic models differently, and vice versa.
    let shared: BTreeSet<&(String, String)> = sch_net
        .keys()
        .filter(|k| pcb_net.contains_key(*k))
        .collect();

    // Two pins on the same PCB net must be on the same schematic net and
    // vice versa. We check by mapping each PCB net to the set of schematic
    // nets its shared members land on, and vice versa: a clean bijection over
    // multi-member nets means identical partitions.
    let mut pcb_to_sch: BTreeMap<i64, BTreeSet<i64>> = BTreeMap::new();
    let mut sch_to_pcb: BTreeMap<i64, BTreeSet<i64>> = BTreeMap::new();
    for k in &shared {
        let s = sch_net[*k];
        let p = pcb_net[*k];
        pcb_to_sch.entry(p).or_default().insert(s);
        sch_to_pcb.entry(s).or_default().insert(p);
    }

    let mut diffs = Vec::new();
    let name_pcb: HashMap<i64, &str> =
        pcb.nets.iter().map(|n| (n.id, n.name.as_str())).collect();
    let name_sch: HashMap<i64, &str> =
        sch.nets.iter().map(|n| (n.id, n.name.as_str())).collect();

    for (p, sset) in &pcb_to_sch {
        // Only multi-member PCB nets matter for partition equivalence.
        let members: Vec<_> = shared
            .iter()
            .filter(|k| pcb_net[**k] == *p)
            .collect();
        if members.len() < 2 {
            continue;
        }
        if sset.len() > 1 {
            diffs.push(format!(
                "PCB net {:?} ({} shared pins) splits across schematic nets {:?}",
                name_pcb.get(p).unwrap_or(&"?"),
                members.len(),
                sset.iter()
                    .map(|s| name_sch.get(s).copied().unwrap_or("?"))
                    .collect::<Vec<_>>()
            ));
        }
    }
    for (s, pset) in &sch_to_pcb {
        let members: Vec<_> = shared
            .iter()
            .filter(|k| sch_net[**k] == *s)
            .collect();
        if members.len() < 2 {
            continue;
        }
        if pset.len() > 1 {
            diffs.push(format!(
                "schematic net {:?} ({} shared pins) merges PCB nets {:?}",
                name_sch.get(s).unwrap_or(&"?"),
                members.len(),
                pset.iter()
                    .map(|p| name_pcb.get(p).copied().unwrap_or("?"))
                    .collect::<Vec<_>>()
            ));
        }
    }
    diffs
}

/// Load the schematic (recursing the hierarchy) and the matching PCB for a
/// project given by its top-file path stem.
fn load_pair(project_dir: &str, stem: &str) -> Option<(ExtractedBoard, ExtractedBoard)> {
    let dir = corpus_dir().join(project_dir);
    let sch_path = dir.join(format!("{stem}.kicad_sch"));
    let pcb_path = dir.join(format!("{stem}.kicad_pcb"));
    let sch = ExtractedBoard::from_kicad_schematic_path(&sch_path).ok()?;
    let pcb_src = std::fs::read_to_string(&pcb_path).ok()?;
    let pcb = ExtractedBoard::from_kicad_pcb(&pcb_src).ok()?;
    Some((sch, pcb))
}

/// Assert exact partition equivalence (over shared pins) for a project, and
/// report a few sanity facts.
fn assert_cross_validates(project_dir: &str, stem: &str, min_nets: usize) {
    let Some((sch, pcb)) = load_pair(project_dir, stem) else {
        eprintln!("corpus pair {project_dir}/{stem} missing; skipping");
        return;
    };

    // Component references should agree (modulo power/flag pseudo-components,
    // which the schematic drops and the PCB never had).
    let sch_refs: BTreeSet<&str> =
        sch.components.iter().map(|c| c.reference.as_str()).collect();
    let pcb_refs: BTreeSet<&str> =
        pcb.components.iter().map(|c| c.reference.as_str()).collect();
    let only_pcb: Vec<_> = pcb_refs.difference(&sch_refs).collect();
    let only_sch: Vec<_> = sch_refs.difference(&pcb_refs).collect();
    assert!(
        only_sch.is_empty(),
        "{stem}: components in schematic but not PCB: {only_sch:?}"
    );
    // PCB-only refs are tolerated (fiducials, mounting hardware) but flagged.
    if !only_pcb.is_empty() {
        eprintln!("{stem}: PCB-only refs (tolerated): {only_pcb:?}");
    }

    let multi = partition(&sch).len();
    assert!(
        multi >= min_nets,
        "{stem}: only {multi} multi-pin schematic nets, expected >= {min_nets}"
    );

    let diffs = diff_partitions(&sch, &pcb);
    assert!(
        diffs.is_empty(),
        "{stem}: {} partition discrepancies:\n{}",
        diffs.len(),
        diffs.join("\n")
    );
    eprintln!(
        "{stem}: cross-validated. {} components, {} multi-pin nets matched exactly.",
        sch.components.len(),
        multi
    );
}

// ---------------------------------------------------------------------------
// Cross-validation: real corpus projects (schematic vs PCB)
// ---------------------------------------------------------------------------

#[test]
fn pic_programmer_cross_validates() {
    // KiCad 10 (20260101), 2-sheet hierarchy. Exact partition match.
    assert_cross_validates("kicad-demos-src/demos/pic_programmer", "pic_programmer", 33);
}

#[test]
fn ecc83_cross_validates() {
    // KiCad 9 (20250114), 2 sheets, tube preamp. Exact partition match.
    assert_cross_validates("kicad-demos-src/demos/ecc83", "ecc83-pp", 8);
}

#[test]
fn complex_hierarchy_cross_validates() {
    // KiCad 9, the *same* sub-sheet instantiated twice on different pages.
    // Exercises per-instance reference resolution: the two instances must
    // expand to distinct designators (RV201 vs RV301) yet identical topology.
    // Exact partition match including the full component set.
    assert_cross_validates(
        "kicad-demos-src/demos/complex_hierarchy",
        "complex_hierarchy",
        20,
    );
}

// ---------------------------------------------------------------------------
// Cross-validation: bus-heavy corpus projects (now exact)
// ---------------------------------------------------------------------------
//
// These three boards drive every bus feature: vector bus labels with per-member
// wire labels, bus entries, buses crossing hierarchical sheet pins (under the
// same name, and under a *different* name with positional member mapping), and
// hidden power pins. They used to only "never over-merge"; with bus expansion
// implemented they must now match their PCB partition exactly, like every other
// validated project.

#[test]
fn interf_u_cross_validates() {
    // KiCad single sheet, two vector buses (PC-DB[0..7], PC-A[0..11]) with bus
    // entries, plus hidden GND/VCC power pins on the PGA and RAM. Exact match.
    assert_cross_validates("kicad-demos-src/demos/interf_u", "interf_u", 100);
}

#[test]
fn video_cross_validates() {
    // KiCad multi-sheet, heavy buses across hierarchical pins, including buses
    // that cross a sheet boundary under a different name (DQ[0..31] feeding a
    // DPC[0..31] sheet pin; TVRAM[..] feeding VRAM[..]) which map member-wise by
    // index. Exact partition match over 189 components.
    assert_cross_validates("kicad-demos-src/demos/video", "video", 300);
}

#[test]
fn kit_dev_coldfire_cross_validates() {
    // KiCad multi-sheet ColdFire/Xilinx dev board: bus sheet pins (AN[0..7],
    // DTIN[0..3], IRQ-[1..7], GPT[0..3], QSPI_CS[0..3]) and many plain
    // hierarchical signals where the named part lives on the parent sheet.
    // Exercises rotate-then-mirror placement (R104/R115/LEDABRT101 at rot 90 +
    // mirror x). Exact partition match over 160 components.
    assert_cross_validates(
        "kicad-demos-src/demos/kit-dev-coldfire-xilinx_5213",
        "kit-dev-coldfire-xilinx_5213",
        150,
    );
}

// ---------------------------------------------------------------------------
// Unit tests on hand-written fixtures
// ---------------------------------------------------------------------------

fn fixture(name: &str) -> Option<ExtractedBoard> {
    let p = fixtures_dir().join(name);
    ExtractedBoard::from_kicad_schematic_path(&p).ok()
}

fn net_of<'a>(b: &'a ExtractedBoard, reference: &str, pin: &str) -> Option<i64> {
    let c = b.component(reference)?;
    c.pins.iter().find(|p| p.number == pin)?.net
}

fn same_net(b: &ExtractedBoard, a: (&str, &str), c: (&str, &str)) -> bool {
    match (net_of(b, a.0, a.1), net_of(b, c.0, c.1)) {
        (Some(x), Some(y)) => x == y,
        _ => false,
    }
}

#[test]
fn fixture_two_resistors_in_series() {
    let Some(b) = fixture("two_resistors.kicad_sch") else {
        eprintln!("fixture missing; skipping");
        return;
    };
    assert_eq!(b.components.len(), 2, "R1 and R2");
    // R1.2 and R2.1 are wired together at the midpoint.
    assert!(
        same_net(&b, ("R1", "2"), ("R2", "1")),
        "series node should be one net"
    );
    // R1.1 and R2.2 are distinct ends.
    assert!(!same_net(&b, ("R1", "1"), ("R2", "2")));
}

#[test]
fn fixture_power_and_labels_unify() {
    let Some(b) = fixture("power_labels.kicad_sch") else {
        eprintln!("fixture missing; skipping");
        return;
    };
    // Both resistor top pins go to a +5V power symbol; they must share a net
    // even though they never touch geometrically.
    assert!(
        same_net(&b, ("R1", "1"), ("R2", "1")),
        "+5V power net must unify both resistors"
    );
    let vcc = b.net_by_name("+5V").expect("+5V net present");
    assert!(b.net_members(vcc.id).len() >= 2);
    // The two bottom pins share a local label "OUT".
    assert!(same_net(&b, ("R1", "2"), ("R2", "2")));
    assert!(b.net_by_name("OUT").is_some());
}

#[test]
fn fixture_unnamed_net_naming() {
    let Some(b) = fixture("two_resistors.kicad_sch") else {
        return;
    };
    // The midpoint net is unnamed → KiCad-style Net-(Rx-PadN) after the
    // lowest member.
    let mid = net_of(&b, "R1", "2").unwrap();
    let name = &b.nets.iter().find(|n| n.id == mid).unwrap().name;
    assert!(
        name.starts_with("Net-(") && name.contains("R1"),
        "unnamed net named {name:?}"
    );
}

#[test]
fn fixture_vector_bus_members() {
    let Some(b) = fixture("bus_vector.kicad_sch") else {
        eprintln!("fixture missing; skipping");
        return;
    };
    // Three resistors. R1.1 and R3.1 both carry the member label D0 (far apart,
    // each mid-span on its wire, both feeding the D[0..1] bus): they unify.
    assert!(
        same_net(&b, ("R1", "1"), ("R3", "1")),
        "bus member D0 must unify R1 and R3"
    );
    // R2.1 is member D1: a different member, and the vector bus label D[0..1]
    // must NOT merge D0 and D1 into one net.
    assert!(
        !same_net(&b, ("R1", "1"), ("R2", "1")),
        "distinct bus members D0 and D1 must stay separate"
    );
    assert!(b.net_by_name("D0").is_some(), "D0 net present");
    assert!(b.net_by_name("D1").is_some(), "D1 net present");
    // The bus label itself must never become a net.
    assert!(
        b.net_by_name("D[0..1]").is_none(),
        "bus label D[0..1] must not appear as a net"
    );
}

#[test]
fn fixture_hierarchical_bus() {
    // A bus crossing a sheet pin: parent ADDR[0..1] sheet pin connects to a
    // child ADDR[0..1] hierarchical label, member-wise. The parent's R-A0/R-A1
    // and the child's RC-A0/RC-A1 must pair by member (A0 with A0, A1 with A1),
    // never cross.
    let Some(b) = fixture("bus_hier_top.kicad_sch") else {
        eprintln!("fixture missing; skipping");
        return;
    };
    assert!(
        same_net(&b, ("RA", "1"), ("RC", "1")),
        "ADDR member A0 must connect parent RA to child RC across the sheet"
    );
    assert!(
        same_net(&b, ("RB", "1"), ("RD", "1")),
        "ADDR member A1 must connect parent RB to child RD across the sheet"
    );
    assert!(
        !same_net(&b, ("RA", "1"), ("RB", "1")),
        "members A0 and A1 must not merge"
    );
    assert!(
        !same_net(&b, ("RA", "1"), ("RD", "1")),
        "member A0 must not cross to member A1's child net"
    );
}

#[test]
fn fixture_bus_alias_crosses_sheet() {
    // End-to-end exercise of a bus-alias *reference* across a sheet boundary
    // (the gap docs/SCHEMATICS.md previously recorded as untested). Both sheets
    // define `(bus_alias "ADDR" (members "A[1..0]"))`. The parent sheet pin and
    // the child hierarchical label are both written `MEM{ADDR}`, which must
    // expand through the alias to the qualified members `MEM.A1`, `MEM.A0`. The
    // member labels on the resistors (`MEM.A1` on RA/RC, `MEM.A0` on RB/RD) then
    // unify member-wise across the boundary. If the alias were *not* expanded,
    // the pin would carry a single literal member `MEM.ADDR` and nothing would
    // cross - the symptom the fix removes.
    let Some(b) = fixture("bus_alias_top.kicad_sch") else {
        eprintln!("fixture missing; skipping");
        return;
    };
    assert!(
        same_net(&b, ("RA", "1"), ("RC", "1")),
        "alias member MEM.A1 must connect parent RA to child RC across the sheet"
    );
    assert!(
        same_net(&b, ("RB", "1"), ("RD", "1")),
        "alias member MEM.A0 must connect parent RB to child RD across the sheet"
    );
    assert!(
        !same_net(&b, ("RA", "1"), ("RB", "1")),
        "distinct alias members MEM.A1 and MEM.A0 must not merge"
    );
    assert!(
        !same_net(&b, ("RA", "1"), ("RD", "1")),
        "member MEM.A1 must not cross to member MEM.A0's net"
    );
    // The qualified member nets exist; the bus/alias expression never becomes a net.
    assert!(b.net_by_name("MEM.A1").is_some(), "MEM.A1 net present");
    assert!(b.net_by_name("MEM.A0").is_some(), "MEM.A0 net present");
    assert!(b.net_by_name("MEM{ADDR}").is_none(), "the bus expression must not be a net");
    assert!(b.net_by_name("MEM.ADDR").is_none(), "the alias must expand, not stay literal");
}

#[test]
fn no_unconnected_components_in_fixtures() {
    for f in ["two_resistors.kicad_sch", "power_labels.kicad_sch"] {
        let Some(b) = fixture(f) else { continue };
        let comps: &[Component] = &b.components;
        for c in comps {
            assert!(
                c.pins.iter().any(|p| p.net.is_some()),
                "{f}: {} fully floating",
                c.reference
            );
        }
    }
}
