// The generated GitHub Actions workflow, in one place.
//
// It was composed inside ChecksView, which was fine while the Checks pane was
// the only thing that could hand it to you. The Export menu offers it too, and
// a second copy of a credential-bearing YAML file is exactly where an
// immutable Action commit can drift back into a mutable tag.

import { ACTION_REPOSITORY, PRIVATE_TOKEN_SECRET, RELEASE_COMMIT, RELEASE_TAG } from './version'

export const workflowExportAvailable = /^[0-9a-f]{40}$/.test(RELEASE_COMMIT)

/** The spec file's stem for a board file name: `watchy.kicad_pcb` -> `watchy`.
 *  Names the downloaded spec and the `spec:` path inside the workflow, so the
 *  two always agree. */
export function specStemFor(boardFileName: string): string {
  const stem = (boardFileName || 'board').replace(/\.[^.]+$/, '')
  // This value becomes both a path segment and an unquoted YAML scalar. Keep
  // the shared exported/downloaded name portable and incapable of adding a
  // comment, newline, traversal, or a second workflow field.
  return stem
    .normalize('NFKD')
    .replace(/[^A-Za-z0-9._-]+/g, '-')
    .replace(/^[.-]+|[.-]+$/g, '') || 'board'
}

/** `.github/workflows/hauksbee-ci.yml`, pinned to THIS build's release commit. */
export function workflowYaml(specStem: string): string {
  if (!workflowExportAvailable) {
    throw new Error('This development build has no immutable release commit; install a released Hauksbee build before exporting CI workflow credentials.')
  }
  return `# .github/workflows/hauksbee-ci.yml
# Generated by hauksbee ${RELEASE_TAG}. Action code is pinned to the exact
# release commit; release assets are independently bound to the same ref below.
name: hardware-ci
on:
  push:
    paths: ["ci/**", "*.toml", ".github/workflows/**", "hardware/**", "firmware/**", "models/**", "**/*.kicad_pcb", "**/*.kicad_sch", "**/*.net", "**/*.brd", "**/*.PcbDoc", "**/*.d356", "**/*.board"]
  pull_request:
    paths: ["ci/**", "*.toml", ".github/workflows/**", "hardware/**", "firmware/**", "models/**", "**/*.kicad_pcb", "**/*.kicad_sch", "**/*.net", "**/*.brd", "**/*.PcbDoc", "**/*.d356", "**/*.board"]
concurrency:
  group: hauksbee-\${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  checks: write
jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Fetch the private hauksbee Action
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: ${ACTION_REPOSITORY}
          ref: ${RELEASE_COMMIT}
          path: .hauksbee-action
          token: ${PRIVATE_TOKEN_SECRET}
          persist-credentials: false
      - name: hauksbee-ci
        uses: ./.hauksbee-action/integrations/github-action
        with:
          hauksbee-token: ${PRIVATE_TOKEN_SECRET}
          hauksbee-ref: ${RELEASE_COMMIT}
          hauksbee-version: ${RELEASE_TAG}
          spec: ci/${specStem}.toml
          junit: hauksbee-ci-results.xml
          publish-report: \${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
`
}
