// The generated GitHub Actions workflow, in one place.
//
// It was composed inside ChecksView, which was fine while the Checks pane was
// the only thing that could hand it to you. The Export menu offers it too, and
// a second copy of a YAML file that pins an action tag is exactly the copy that
// keeps the tag nobody published.

import { ACTION_REPOSITORY, PRIVATE_TOKEN_SECRET, RELEASE_TAG } from './version'

/** The spec file's stem for a board file name: `watchy.kicad_pcb` -> `watchy`.
 *  Names the downloaded spec and the `spec:` path inside the workflow, so the
 *  two always agree. */
export function specStemFor(boardFileName: string): string {
  return (boardFileName || 'board').replace(/\.[^.]+$/, '')
}

/** `.github/workflows/hauksbee-ci.yml`, pinned to THIS build's release tag. */
export function workflowYaml(specStem: string): string {
  return `# .github/workflows/hauksbee-ci.yml
# Generated by hauksbee ${RELEASE_TAG}. The action below is pinned to that tag; change it
# to match whichever hauksbee version you actually have installed, and keep it pinned.
name: hardware-ci
on:
  push:
    paths: ["hardware/**", "firmware/**", "ci/**.toml"]
  pull_request:
    paths: ["hardware/**", "firmware/**", "ci/**.toml"]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch the private hauksbee Action
        uses: actions/checkout@v4
        with:
          repository: ${ACTION_REPOSITORY}
          ref: ${RELEASE_TAG}
          path: .hauksbee-action
          token: ${PRIVATE_TOKEN_SECRET}
      - name: hauksbee-ci
        uses: ./.hauksbee-action/integrations/github-action
        with:
          hauksbee-token: ${PRIVATE_TOKEN_SECRET}
          spec: ci/${specStem}.toml
          junit: hauksbee-ci-results.xml
`
}
