//! galvani-mcu: generalized MCU emulation bridge.
//!
//! Provides a [`Mcu`] trait for driving a simulated microcontroller, plus a
//! simavr-backed [`AvrMcu`] implementation.  All Tarski-specific logic (MCP4728
//! decode, 74HC595 readback, neuron simulation) lives in higher-level crates;
//! this crate is pure emulation plumbing.
//!
//! # Licensing note
//! This crate links libsimavr (GPL-3.0).  Any binary built from it is subject
//! to the GPL.  See the NOTICE file shipped alongside this crate.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

/// Raw simavr FFI bindings generated by bindgen.
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/simavr_bindings.rs"));
}

pub mod avr;
pub mod traits;

pub use traits::{I2cEvent, McuState, Mcu, PinId, SpiEvent};
pub use avr::AvrMcu;
