//! galvani-mcu: generalized MCU emulation bridge.
//!
//! Provides a [`Mcu`] trait for driving a simulated microcontroller, plus two
//! backends behind the uniform trait:
//!   - [`AvrMcu`] (feature `avr`): in-process AVR via libsimavr FFI.
//!   - [`RenodeBackend`] (feature `renode`): STM32 / nRF52 / RISC-V (and more)
//!     by driving an external headless Renode process over its Monitor TCP
//!     protocol and a UART socket terminal.
//!
//! Both backends present the identical lockstep surface (`run_micros`, GPIO/
//! ADC/UART exchange via [`PinId`] and byte streams), so the engine scheduler
//! couples to either without change. All board-specific logic (MCP4728 decode,
//! 74HC595 readback, neuron simulation) lives in higher-level crates; this
//! crate is pure emulation plumbing.
//!
//! # Licensing note
//! With the `avr` feature, this crate links libsimavr (GPL-3.0) and any binary
//! built from it is subject to the GPL. The `renode` backend links nothing
//! native (it talks to Renode over sockets), so a `--no-default-features
//! --features renode` build is GPL-free.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

/// Raw simavr FFI bindings generated by bindgen.
#[cfg(feature = "avr")]
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/simavr_bindings.rs"));
}

#[cfg(feature = "avr")]
pub mod avr;
pub mod traits;

#[cfg(feature = "renode")]
pub mod renode;

pub use traits::{I2cEvent, McuState, Mcu, PinId, SpiEvent};

#[cfg(feature = "avr")]
pub use avr::AvrMcu;

#[cfg(feature = "renode")]
pub use renode::{RenodeBackend, RenodeConfig};
